# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
            ],
            options={
                'verbose_name': '베스트 게시물',
                'verbose_name_plural': '베스트 게시물',
            },
        ),
        migrations.CreateModel(
            name='BestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
            ],
            options={
                'verbose_name': '베스트 댓글',
                'verbose_name_plural': '베스트 댓글',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='URL 표현')),
                ('ko_name', models.CharField(max_length=32, unique=True, verbose_name='국문 분류 명칭')),
                ('en_name', models.CharField(max_length=32, unique=True, verbose_name='영문 분류 명칭')),
                ('ko_description', models.CharField(max_length=256, verbose_name='국문 분류 설명')),
                ('en_description', models.CharField(max_length=256, verbose_name='영문 분류 설명')),
            ],
            options={
                'verbose_name': '게시물 분류',
                'verbose_name_plural': '게시물 분류',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제 시간')),
                ('content', models.TextField(verbose_name='본문')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명')),
                ('is_content_erotic', models.BooleanField(default=False, verbose_name='성인/음란성 내용')),
                ('is_content_social', models.BooleanField(default=False, verbose_name='정치/사회성 내용')),
                ('use_signature', models.BooleanField(default=True, verbose_name='서명 사용')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Document')),
                ('title', models.CharField(max_length=32, verbose_name='제목')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
            },
            bases=('core.document',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Document')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
            bases=('core.document',),
        ),
    ]
