# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='session.UserProfile', verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Document', verbose_name='상위 문서'),
        ),
        migrations.AddField(
            model_name='bestcomment',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best', to='core.Comment', verbose_name='원본 댓글'),
        ),
        migrations.AddField(
            model_name='bestarticle',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best', to='core.Article', verbose_name='원본 게시물'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(db_index=True, related_name='articles', to='core.Category', verbose_name='분류 목록'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='session.UserProfile', verbose_name='작성자'),
        ),
    ]
