# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_comment',
            field=models.BooleanField(default=False, verbose_name='댓글'),
        ),
    ]
